sudo: required
dist: trusty
language: generic

# TODO: investigate whether Tavis' CI stages could be used here
env:
    - GHCVER=8.2.2 TEST_PART=CORE1
    - GHCVER=8.2.2 TEST_PART=CORE2
    - GHCVER=8.2.2 TEST_PART=PROFILING
    - GHCVER=8.2.2 TEST_PART=GHCJS

addons:
    apt:
        sources:
            - hvr-ghc
            - sourceline: 'deb https://deb.nodesource.com/node_6.x trusty main'
              key_url: 'https://deb.nodesource.com/gpgkey/nodesource.gpg.key'
        packages:
            - build-essential
            - nodejs
            - cabal-install-2.2
            - ghc-8.2.2
            - alex-3.1.7
            - happy-1.19.5

before_install:
    - nvm install 8
    - export PATH=$HOME/.cabal/bin:/opt/ghc/$GHCVER/bin:/opt/cabal/2.2/bin:/opt/alex/3.1.7/bin:/opt/happy/1.19.5/bin:$PATH

install:
    - travis_retry cabal update
    - cabal install --only-dependencies --enable-tests --enable-benchmarks
    - cabal install --enable-tests --enable-benchmarks -v -j1 --ghc-options="+RTS -c -RTS"
    - ghcjs --version
    - ghcjs-boot --version
    - ./test/runTravis.sh boot
    - ghcjs-pkg list

script:
    - ./test/runTravis.sh test

notifications:
  irc:
    channels: "irc.freenode.net#ghcjs"
    skip_join: true
  email: true

sudo: false
