# the source tree needs to be "booted" for this stack.yaml file to be usable:
#
# $ git submodule update --init --recursive
# $ (cd ghc && ./boot && ./configure && make)
# $ ./utils/makePackages.sh
#

#resolver: lts-10.3
resolver: nightly-2018-05-10
packages:
  - .
  - ./lib/ghc-api-ghcjs
  - ./lib/ghci-ghcjs
  - ./lib/ghcjs-th
  - ./lib/haddock-api-ghcjs
  - ./lib/haddock-library-ghcjs
  - ./lib/template-haskell-ghcjs

extra-deps:
- Cabal-2.2.0.1
- base-4.11.1.0
- ghc-boot-8.4.2
- ghc-boot-th-8.4.2
- parsec-3.1.13.0
- text-1.2.3.0
- cabal-doctest-1.0.6
- haskell-src-exts-1.20.2
- git: https://github.com/simonmar/ghc-paths.git
  commit: 6f3af8f98e538e08324bc97ceaf41d352e9d2732
- haskell-src-meta-0.8.0.2
- lens-4.16.1
- git: http://git.haskell.org/packages/hpc.git
  commit: 91f520cb9725d812fa93b57bca1d8dbd72c88dd5

- wl-pprint-text-1.2.0.0
    #allow-newer: true
- base-compat-0.10.1
- aeson-1.3.1.1
